alter table students
  add column if not exists nis_user text,
  add column if not exists color text,
  add column if not exists cpf_cns text,
  add column if not exists is_allergic boolean not null default false,
  add column if not exists allergy_details text,
  add column if not exists shoe_size text,
  add column if not exists clothing_size text,
  add column if not exists has_health_issues boolean not null default false,
  add column if not exists health_issues_details text,
  add column if not exists has_disability boolean not null default false,
  add column if not exists disability_details text,
  add column if not exists school_name text,
  add column if not exists school_grade text,
  add column if not exists school_shift text,
  add column if not exists address_street text,
  add column if not exists address_neighborhood text,
  add column if not exists address_reference text,
  add column if not exists address_extra text,
  add column if not exists guardian_cpf text,
  add column if not exists guardian_nis text,
  add column if not exists guardian_relationship text,
  add column if not exists guardian_workplace text,
  add column if not exists family_benefit boolean not null default false,
  add column if not exists family_benefit_details text,
  add column if not exists family_members jsonb,
  add column if not exists cras_status text,
  add column if not exists cras_link_reason text,
  add column if not exists cras_referral_agency text,
  add column if not exists cras_technician text,
  add column if not exists scfv_insertion_date date,
  add column if not exists scfv_update_date date,
  add column if not exists scfv_frequency_days text[],
  add column if not exists scfv_shift text[],
  add column if not exists scfv_group text,
  add column if not exists scfv_instructor text,
  add column if not exists scfv_boarding text,
  add column if not exists scfv_disembarkation text;
